#!/bin/sh
if [[ -f "/tmp/BackOn/Update/info/runUpdateODS" ]]; then
	runUpdateODS="$(cat "/tmp/BackOn/Update/info/runUpdateODS")"
fi
if [[ -f "/tmp/BackOn/Update/info/UpdateBuildType" ]]; then
	UpdateBuildType="$(cat "/tmp/BackOn/Update/info/UpdateBuildType")"
fi
if [[ -f "/tmp/BackOn/Update/info/updateWithDEBInstall" ]]; then
	updateWithDEBInstall="$(cat "/tmp/BackOn/Update/info/updateWithDEBInstall")"
fi
if [[ -f "/tmp/BackOn/Update/info/UpdaterVersion" ]]; then
	UpdaterVersion="$(cat "/tmp/BackOn/Update/info/UpdaterVersion")"
else
	UpdaterVersion=1
fi
if [[ -f "/tmp/BackOn/Update/info/showLog" ]]; then
	showLog="$(cat "/tmp/BackOn/Update/info/showLog")"
fi
if [[ -f "/tmp/BackOn/Update/info/applyColorScheme" ]]; then
	applyColorScheme="$(cat "/tmp/BackOn/Update/info/applyColorScheme")"
fi
if [[ -f "/tmp/BackOn/Update/info/UpdateBuildVersion" ]]; then
	UpdateBuildVersion="$(cat "/tmp/BackOn/Update/info/UpdateBuildVersion")"
fi

function Update1(){
	applyPurple
	echo "UpdaterVersion : 1"
	applyNoColor
	cp backon.sh /usr/bin/backon
	chmod +x /usr/bin/backon
	if [[ -f /var/mobile/Library/Preferences/BackOn/runUpdateODS ]]; then
		if [[ "$(cat "/var/mobile/Library/Preferences/BackOn/runUpdateODS")" == YES ]]; then
			backon -ods; exit 0
		fi
	fi
	backon; exit 0
}

function Update2(){
	if [[ "${showLog}" == YES ]]; then
		applyPurple
		echo -e "UpdaterVersion : 2"
		echo -e "runUpdateODS : ${runUpdateODS}"
		echo -e "UpdateBuildType : ${UpdateBuildType}"
		echo -e "updateWithDEBInstall : ${updateWithDEBInstall}"
		echo -e "UpdaterVersion : ${UpdaterVersion}"
		echo -e "showLog : ${showLog}"
		echo -e "UpdateBuildVersion : ${UpdateBuildVersion}"
		applyNoColor
		showPressAnyKeyToContinue
	fi
	if [[ "${updateWithDEBInstall}" == YES && ! "${UpdateBuildType}" == alpha ]]; then
		if [[ "${showLog}" == YES ]]; then
			applyPurple
			dpkg -i "/tmp/BackOn/Update/master/BackOn-master/deb-${UpdateBuildType}/${UpdateBuildType}-${UpdateBuildVersion}.deb"
			applyNoColor
		else
			dpkg -i "/tmp/BackOn/Update/master/BackOn-master/deb-${UpdateBuildType}/${UpdateBuildType}-${UpdateBuildVersion}.deb" > /dev/null 2>&1
		fi
	else
		cp "/tmp/BackOn/Update/master/BackOn-master/${UpdateBuildType}/backon.sh" /usr/bin/backon
		chmod +x /usr/bin/backon
	fi
	runBackOn
}

function applyRed(){
	if [[ "${applyColorScheme}" == YES ]]; then
		echo -e -n "\033[0;31m"
	fi
}

function applyPurple(){
	if [[ "${applyColorScheme}" == YES ]]; then
		echo -e -n "\033[1;35m"
	fi
}

function applyLightCyan(){
	if [[ "${applyColorScheme}" == YES ]]; then
		echo -e -n "\033[1;36m"
	fi
}

function applyNoColor(){
	if [[ "${applyColorScheme}" == YES ]]; then
		echo -e -n "\033[0m"
	fi
}

function showPressAnyKeyToContinue(){
	applyLightCyan
	read -s -n 1 -p "Press Any key to continue..."
	applyNoColor
	echo -e
}

function runBackOn(){
	if [[ "${runUpdateODS}" == YES ]]; then
		backon -ods
	else
		backon
	fi
	exit 0
}

##############################

if [[ "${UpdaterVersion}" == 1 ]]; then
	Update1
elif [[ "${UpdaterVersion=}" == 2 ]]; then
	Update2
else
	applyRed
	echo "ERROR!"
	applyNoColor
	exit 1
fi